### ISSUE TITLE
Camera distortion

### ISSUE THREAD

**Issue by v-pnk** [WaldJohannaU/RIO10#13]
Hi!

Thank you very much for the dataset!

I have two questions about the camera distortion parameters. The [intrinsics.txt](https://github.com/WaldJohannaU/RIO10/blob/master/data/intrinsics.txt) file contains only pinhole camera parameters, but the camera.yaml files in the dataset contain 3 distortion parameters:

```
camera_intrinsics:
  height: 960
  width: 540
  model: [756.02630615, 756.83215332, 270.41879272, 492.88940430]
  distortion: [0.0339812118397886, -0.0400683368921275, 0.0348718094889709]
```

- Are the images in the dataset distorted or undistorted?
- Are the 3 distortion parameters corresponding to radial distortion coefficients?

Thank you for any clarification.
